#!/bin/bash -e

## Copyright (C) 2012 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Early setup steps that must run before sanity checks. Note that this script
## must not source 'pre' or 'variables', and must not depend on early
## dependencies.

## style-ok: allow-echo -- the only 'echo' occurrences are inside strings.

## Unconditionally set on purpose.
DM_MYDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# shellcheck source=../packages/kicksecure/helper-scripts/usr/libexec/helper-scripts/check_runtime.bsh
source "${DM_MYDIR}/../packages/kicksecure/helper-scripts/usr/libexec/helper-scripts/check_runtime.bsh" || true
if ! declare -F was_executed >/dev/null; then
   printf '%s\n' "$0: ERROR: cannot source check_runtime.bsh!" >&2
   exit 1
fi

## Doesn't need an exit guard since we now know helper-scripts exists.
# shellcheck source=../packages/kicksecure/helper-scripts/usr/libexec/helper-scripts/package_installed_check.sh
source "${DM_MYDIR}/../packages/kicksecure/helper-scripts/usr/libexec/helper-scripts/package_installed_check.sh"

install_required_packages() {
   local required_package_item all_present="true"

   ## Skip trying to install the dependencies if they're all installed.
   # shellcheck disable=SC2086
   for required_package_item in ${dist_build_early_dependencies} ; do
      if ! pkg_installed "${required_package_item}" ; then
         true "INFO: early dependency '${required_package_item}' missing; installing the full early set."
         all_present="false"
         break
      fi
   done
   if [ "${all_present}" = "true" ]; then
      true "INFO: all early build dependencies already installed."
      return 0
   fi

   ## Using the build system's already existing APT sources list.
   ## As configured by the local system administrator.
   ##
   ## Not using the following command line options:
   #-o Dir::Etc::sourcelist="$dist_build_sources_list_primary" \
   #-o Dir::Etc::sourceparts="-" \
   ## Because dist_build_sources_list_primary requires approx.

   # shellcheck disable=SC2086
   retry_run -- \
   ${SUDO_TO_ROOT} \
      apt-get \
         "${DIST_APTGETOPT_WITHOUT_APT_CACHE[@]}" \
         update

   # shellcheck disable=SC2086
   retry_run -- \
   ${SUDO_TO_ROOT} \
      apt-get \
         "${DIST_APTGETOPT_WITHOUT_APT_CACHE[@]}" \
         ${apt_unattended_opts} \
         --no-install-recommends \
         --yes \
         install \
         ${dist_build_early_dependencies}
}

main() {
   set -x
   set -o errexit
   set -o nounset
   set -o pipefail
   set -o errtrace
   shopt -s inherit_errexit
   shopt -s shift_verbose
   export LC_ALL=C

   true "INFO: Currently running script: ${BASH_SOURCE[0]} $*"

   cd "${DM_MYDIR}"
   cd ..

   install_required_packages
}

if was_executed "${BASH_SOURCE[0]}"; then
   main "$@"
fi
