debian https://deb.debian.org/debian
debian-security https://deb.debian.org/debian-security
debian-fasttrack https://fasttrack.debian.net/debian-fasttrack
## The snapshot timestamp is in
## build_sources/debian_stable_frozen_clearnet.sources as a path segment, which
## approx forwards.
debian-frozen https://snapshot.debian.org/archive/debian
debian-security-frozen https://snapshot.debian.org/archive/debian-security
tpo https://deb.torproject.org/torproject.org
ubuntu http://us.archive.ubuntu.com/ubuntu
kicksecure https://deb.kicksecure.com
whonix https://deb.whonix.org
oracle https://download.virtualbox.org/virtualbox/debian/

$cache /var/cache/approx-derivative-maker
$verbose true
$debug true
