#!/bin/bash

## Copyright (C) 2026 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## AI-Assisted

## FIXME: Script contains 'lb' in the name, must be renamed, this script might
## become obsolete when we remove live-build.
##
## FIXME: If this script isn't completely obsoleted, callers may need to
## ensure they are not "within" the directory being unmounted. This is because
## we no longer use 'umount --lazy' due to safety concerns. Do NOT do anything
## about this unless it is confirmed that this script is still necessary.

set -x
set -o errexit
set -o nounset
set -o pipefail
set -o errtrace
shopt -s inherit_errexit
shopt -s shift_verbose

true "INFO: Currently running script: ${BASH_SOURCE[0]} $*"

MYDIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )"

source "${MYDIR}/pre"
source "${MYDIR}/variables"

main() {
   local live_build_folder

   live_build_folder="${dist_binary_build_folder}/live-build"

   if [ ! -d "${live_build_folder}" ]; then
      true "INFO: '${live_build_folder}' does not exist, nothing to unmount, ok."
      return 0
   fi

   if ! ${SUDO_TO_ROOT} "${MYDIR}/unmount-tree" -- "${live_build_folder}" ; then
      printf '%s\n' "WARNING: ${BASH_SOURCE[0]}: do NOT 'rm -rf' '${live_build_folder}' until the mounts listed above are unmounted! Unmount them manually, or the next build's 'lb clean' will." >&2
   fi

   sync
}

main "$@"
