#!/bin/bash

## Copyright (C) 2012 - 2025 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## You can drop your custom build config files in:
## ${HOMEVAR}/buildconfig.d
## Files need to have the '.conf' file extension.
##
## For example with HOMEVAR=/home/user, drop them in
## /home/user/buildconfig.d/. Easier than dropping in
## /home/user/derivative-maker/buildconfig.d, because
## you do not have to git commit them.
