#!/bin/bash

## Copyright (C) 2012 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Optionally build packages for multiple architectures at once.
#default_if_empty make_cross_build_platform_list "amd64 arm64"
