#!/bin/bash

## Copyright (C) 2012 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Build Script Upgrade Build Machine
## defaults to: upgrade build machine
## When not turned off below, it will run apt-get update and
## apt-get dist-upgrade before in build step "prepare build machine".
## as well.
dist_build_upgrade_build_machine='true'
