#!/bin/bash

## Copyright (C) 2012 - 2026 ENCRYPTED SUPPORT LLC <adrelanos@whonix.org>
## See the file COPYING for copying conditions.

## Build Script Unattended Package Install
## default to: do not install packages unattended
## Sets dpkg option --force-confold while upgrading.
## When not turned off below, it will not install packages without configuration
## questions.
## Debian frontend is set to noninteractive while running the upgrade
## as well.
default_if_empty dist_build_unattended_pkg_install 'true'
export dist_build_unattended_pkg_install
